#!/usr/bin/env bash

set -e

# Exporting the specific shell we want to work with:

SHELL='/bin/bash'
export SHELL

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "$BASEDIR"
git submodule sync --quiet --recursive
git submodule update --init --recursive

# Install ZSH if neccessary
[ ! -x /usr/bin/zsh ] && DEBIAN_FRONTEND=noninteractive apt-get -y install zsh zsh-common zsh-autosuggestions zsh-syntax-highlighting >/dev/null

# Linking dotfiles:

run_dotbot () {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    -c "$config" $ARGS
}

run_dotbot 'steps/terminal.yml' || true
if [ "$CODESPACES" = true ]; then
 run_dotbot 'steps/codespaces.yml' || true
else
 run_dotbot 'steps/dependencies.yml' || true
fi
run_dotbot 'steps/vscode.yml' || true
